[package]
name = "fractal_rs"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE.txt"
license = "mit"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.36.0"
num-complex = "0.4.4"
rayon = "1.8.0"